import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { createClient } from 'contentful'
import styles from '../styles/Home.module.css'

/*
https://medium.com/bigpanda-engineering/dark-theme-with-styled-components-a573dd898e2a
https://styled-components.com/docs/api#themeprovider

Contentful
https://contentful.github.io/contentful.js/contentful/9.1.4/
*/

const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
})

export default function Home({ entries }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contentful Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Contentful Courses!
        </h1>
        <p className={styles.description}>
          Below is a list of available courses{' '}
        </p>

        <div className={styles.grid}>
          {entries.items.map((item) => {
            return (
              <Link href={`/${item.fields.slug}`} key={item.sys.id}>
                <div className={styles.card}>
                  <h2>{item.fields.title}</h2>
                  <p>{item.fields.shortDescription}</p>
                </div>
              </Link>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  const entries = await client.getEntries({
    content_type: 'course'
  });
  return {
    props: {
      entries,
    }
  }
}
